version: '3.9'

services:
  user-svc:
    image: 'go-mts-user-svc:latest'
    build: user-svc
    ports:
      - "8080:8080"
    depends_on:
      user_db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=password
  user_db:
    container_name: mts_user_db
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5437:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
#    command: ["bash", "-c", "pg_isready -U postgres -d postgres && psql -U postgres -d postgres -f /user-svc/schema/000001_init.up.sql"]
#    volumes:
#      - ./.database/postgres/user_data:/var/lib/postgresql/data
networks:
  host:
