apiVersion: "1.0.0"

app:
  name: "driver"
  env: "local"

logger:
  level: "trace"
  encoding: "console"

metrics:
  enable: false
  dsn: "<sentry_dsn_for_service>"

graceful_shutdown:
  delay: "5s"
  wait_timeout: "5s"
  callback_timeout: "2s"

http:
  host: "localhost"
  port: 8080
  read_timeout: "1s"
  write_timeout: "1s"

location_client:
  uri: "http://localhost:9090"

mongo:
  database: driver
  uri: "mongodb://localhost:27017,localhost:27018,localhost:27019/driver?replicaSet=rs0&authSource=admin&readPreference=primaryPreferred"

migrations_mongo:
  uri: "mongodb://localhost:27017,localhost:27018,localhost:27019/driver?replicaSet=rs0&authSource=admin&readPreference=primaryPreferred"
  path: "./projects/driver/migrations"
  enabled: true
