apiVersion: "1.0.0"

app:
  name: "location"
  env: "local"

logger:
  env: "dev" # "prod"
  level: "debug"
  outputs:
    - "stdout"
  error_outputs:
    - "stderr"
  encoding: "json"
  sentry_dsn: ""
  sentry_level: "error"

metrics:
  enable: false
  dsn: "<sentry_dsn_for_service>"

http:
  host: "localhost"
  port: 8080
  read_timeout: "1s"
  write_timeout: "1s"

postgres:
  host: "localhost"
  port: 5444
  username: "postgres"
  password: "password"
  db-name: "postgres"
  ssl-mode: "disable"
  migration: "projects/location/migrations"

graceful_shutdown:
  delay: "5s"
  wait_timeout: "5s"
  callback_timeout: "2s"

tracer:
  enable: false
  exp_target: "jaeger-all-in-one:4317"
