apiVersion: "1.0.0"

app:
  name: "location"
  env: "local"

logger:
  env: "dev" # "prod"
  level: "debug"
  outputs:
    - "stdout"
  error_outputs:
    - "stderr"
  encoding: "json"
  sentry_dsn: ""
  sentry_level: "error"

metrics:
  enable: false
  dsn: "<sentry_dsn_for_service>"

graceful_shutdown:
  delay: "3s"
  wait_timeout: "15s"
  callback_timeout: "5s"

http:
  host: "0.0.0.0"
  port: 8084
  read_timeout: "1s"
  write_timeout: "1s"

postgres:
  host: "location_db"
  port: 5432
  username: "postgres"
  password: "password"
  dbname: "location_db"
  sslmode: "disable"
  migration: "migrations"

tracer:
  enable: true
  exp_target: "host.docker.internal:4317"
