apiVersion: "1.0.0"

app:
  name: "location"
  env: "local"

logger:
  env: "dev" # "prod"
  level_logger: "debug"
  level_sentry: "error"
  outputs:
    - "stdout"
  error_outputs:
    - "stderr"
  encoding: "json"
  sentry_dsn: ""

metrics:
  enable: false
  dsn: "<sentry_dsn_for_service>"

graceful_shutdown:
  delay: "5s"
  wait_timeout: "5s"
  callback_timeout: "2s"

http:
  host: "0.0.0.0"
  port: 8084
  read_timeout: "1s"
  write_timeout: "1s"

postgres:
  host: "location_db"
  port: 5432
  username: "postgres"
  password: "password"
  db-name: "location_db"
  ssl-mode: "disable"
  migration: "migrations"

tracer:
  enable: true
  exp_target: "host.docker.internal:4317"
